GET http://localhost:3003/api/icecreams

###
GET http://localhost:3003/api/icecreams/id/64f8b3e6c10621839a8e8db8

###
GET http://localhost:3003/api/icecreams/name/Sixth%20ice-cream!

###
POST http://localhost:3003/api/icecreams HTTP/1.1
content-type: application/json

{
    "name": "seventh",
    "isUserGenerated": true,
    "userId": "dgfbnogrb"
}
