GET http://localhost:3003/api/icecreams

###
GET http://localhost:3003/api/icecreams/id/6500bbaabd5bd2af1ef72c2b

###
GET http://localhost:3003/api/icecreams/name/abominable%20snowman

###
POST http://localhost:3003/api/icecreams HTTP/1.1
content-type: application/json

{
    "name": "jumbo staircase",
    "isUserGenerated": true,
    "userId": "leewiz"
}

###
GET http://localhost:3003/api/icecreams/suggestions/3

