POST http://localhost:3003/api/words/noun HTTP/1.1
content-type: application/json

{
    "name": "dog",
    "count": 0
}

###
GET http://localhost:3003/api/words/noun 

###
POST http://localhost:3003/api/words/adjective HTTP/1.1
content-type: application/json

{
    "name": "cloudy",
    "count": 0
}

###
GET http://localhost:3003/api/words/adjective 
